# POST http://localhost:3001/api/notes
# Content-Type: application/json

# {
#     "content": "This is my first content1"

# }


# POST http://localhost:3001/api/users
# Content-Type: application/json

# {
#     "username":"ram",
#     "name": "Ram Kc"

# }

POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username":"ram",
    "password": "secret" 

}

# PUT http://localhost:3001/api/notes/1
# Content-Type: application/json

# {
#     "important": true 

# }