POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "This is my first content1"

}

# PUT http://localhost:3001/api/notes/1
# Content-Type: application/json

# {
#     "important": true 

# }