# get http://localhost:3001/api/notes

### Delete a note

# delete http://localhost:3001/api/notes/68e8ba304e470babc4f13e21

### adding the new note

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "name":"Krish",
    "username":"krish1234",
    "password":"krish12345"

}

# PUT http://localhost:3001/api/notes/68e8ba4b6bfcac03f7d865d4
# Content-Type: application/json

# {
#     "content": "Updated note content",
#     "important": true
# }