# get http://localhost:3001/api/notes

### Delete a note

# delete http://localhost:3001/api/notes/68e8ba304e470babc4f13e21

### adding the new note

# POST http://localhost:3001/api/login
# Content-Type: application/json

# {
#     "username":"gopalnarayan12345",
#     "password":"password12345"

# }

# POST http://localhost:3001/api/notes
# Content-Type: application/json

# {
#     "content": "Beauty of Nature",
#     "important": true,
#     "userId":"68f1d384db2164048cf05a13"
# }

# GET http://localhost:3001/api/users